[build]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=-Wl,--gc-sections",  # Remove unused sections
    "-C", "panic=abort"                  # Required for panic_immediate_abort
]

[profile.minsizerel]
rustflags = [
    "-C", "force-frame-pointers=no",     # Disable frame pointers
    "-C", "no-redzone=yes",             # Disable stack redzone
    "-Z", "location-detail=none",       # Disable location details in errors
    "-Z", "fmt-debug=none"              # Disable debug formatting
]
